regression_1 <- read.csv("Regression CSVs/Number of Undergraduate Schools_Undergraduate Attrition by Cohort Size_all.csv")
lm_1 <- lm(Undergraduate.Attrition.by.Cohort.Size~Number.of.Undergraduate.Schools,data=regression_1)
summary(lm_1)
cor(lm_1)
regression_2 <- read.csv("Regression CSVs/Number of Undergraduate Schools_Undergraduate ATtrition by Cohort Size_all-.csv")
lm_2 <- lm(Undergraduate.Attrition.by.Cohort.Size~Number.of.Undergraduate.Schools,data=regression_2)
summary(lm_2)
cor(lm_2)
plot(regression_2$Number.of.Undergraduate.Schools,resid(lm_2))
summary(lm(data=regression_2))
cor(regression_2$Number.of.Undergraduate.Schools,regression_2$Undergraduate.Attrition.by.Cohort.Size)