chedi <- read.csv("Dataframes/Inflow vs CHEDI.csv")
lm_chedi <- lm(chedi$Scaled.Inflow~chedi$CHEDI,data= chedi)
summary(lm_chedi)
chedi_grp <- read.csv("Dataframes/Inflow vs CHEDI and GRP.csv")
lm_chedi_grp <- lm(chedi_grp$Scaled.Inflow~chedi_grp$CHEDI+chedi_grp$Relative.GRP,data=chedi_grp)
summary(lm_chedi_grp)
chedi_grp_science <- read.csv("Dataframes/Inflow vs CHEDI and GRP and Science.csv")
lm_chedi_grp_science <- lm(chedi_grp_science$Scaled.Inflow~chedi_grp_science$CHEDI+chedi_grp_science$Relative.GRP+chedi_grp_science$Science.Cutoff,data=chedi_grp_science)
summary(lm_chedi_grp_science)
